require_relative 'skatista/popula_skatista'
require_relative 'participacao/popula_participacao'
require_relative 'campeonato/popula_campeonato'
require_relative 'categoria/popula_categoria'
require_relative 'local/popula_local'
